// 默认配置
import {AppConfig} from "./AppConfig";

export const DEFAULT_APP_CONFIG: AppConfig = {
    general: {
        language: 'zh-CN',
        theme: 'auto',
        proxyMode: 'system',
        spellCheck: true,
        hardwareAcceleration: true,
        autoStart: false,
        minimizeToTray: true,
        closeToTray: false,
        showTrayIcon: true,
        checkUpdatesOnStartup: true,
        assistantMessages: true,
        backup: true,
        knowledgeBase: true,
        anonymousReporting: true,
    },
    display: {
        theme: '深色',
        themeColor: '#00B96B',
        transparentWindow: true,
        navbarPosition: '左侧',
        zoomLevel: 100,
        topicPosition: '左侧',
        autoSwitchTopic: false,
        showTopicTime: true,
        pinTopicTop: false,
        modelIconType: '模型图标',
        fontSize: 14,
        fontFamily: 'system-ui, -apple-system, sans-serif',
        lineHeight: 1.6,
        showLineNumbers: false,
        showMinimap: false,
        wordWrap: true,
        cursorStyle: 'line',
    },
    models: {
        providers: {},
        defaultProvider: '',
        defaultModel: '',
    },
    search: {
        searchProvider: 'Tavily (API 密钥)',
        apiKey: '',
        apiUrl: 'https://api.tavily.com',
        includeAnswer: true,
        maxResults: 5,
        compressionMethod: '不压缩',
        blacklistSites: [],
        enableFullTextSearch: true,
        enableSemanticSearch: false,
        indexingEnabled: true,
    },
    shortcuts: {
        shortcuts: [
            {
                id: 'display-hidden-app',
                name: '显示/隐藏应用',
                description: '快速显示或隐藏应用窗口',
                defaultKey: '按下快捷键',
                currentKey: '按下快捷键',
                category: 'app',
                enabled: true,
            },
            {
                id: 'quick-assistant',
                name: '快捷助手',
                description: '快速打开AI助手对话',
                defaultKey: '⌘ + E',
                currentKey: '⌘ + E',
                category: 'assistant',
                enabled: true,
            },
            {
                id: 'open-assistant',
                name: '开关助手手',
                description: '开启或关闭助手功能',
                defaultKey: '按下快捷键',
                currentKey: '按下快捷键',
                category: 'assistant',
                enabled: true,
            },
            {
                id: 'assistant-word',
                name: '划词助手：取词',
                description: '选中文字后快速取词翻译',
                defaultKey: '按下快捷键',
                currentKey: '按下快捷键',
                category: 'assistant',
                enabled: true,
            },
            {
                id: 'exit-fullscreen',
                name: '退出全屏',
                description: '退出全屏模式',
                defaultKey: 'Escape',
                currentKey: 'Escape',
                category: 'display',
                enabled: true,
            },
            {
                id: 'new-conversation',
                name: '新建话题',
                description: '创建新的对话话题',
                defaultKey: '⌘ + N',
                currentKey: '⌘ + N',
                category: 'conversation',
                enabled: true,
            },
            {
                id: 'toggle-assistant-tips',
                name: '切换助手显示',
                description: '显示或隐藏助手提示信息',
                defaultKey: '⌘ + [',
                currentKey: '⌘ + [',
                category: 'assistant',
                enabled: true,
            },
            {
                id: 'toggle-conversation-tips',
                name: '切换话题显示',
                description: '显示或隐藏话题列表',
                defaultKey: '⌘ + ]',
                currentKey: '⌘ + ]',
                category: 'conversation',
                enabled: true,
            },
            {
                id: 'copy-last-message',
                name: '复制上一条消息',
                description: '快速复制最后一条对话消息',
                defaultKey: '⌘ + ⇧ + C',
                currentKey: '⌘ + ⇧ + C',
                category: 'conversation',
                enabled: true,
            },
            {
                id: 'search-messages',
                name: '搜索消息',
                description: '在对话历史中搜索消息',
                defaultKey: '⌘ + ⇧ + F',
                currentKey: '⌘ + ⇧ + F',
                category: 'conversation',
                enabled: true,
            },
            {
                id: 'clear-messages',
                name: '清空消息',
                description: '清空当前对话的所有消息',
                defaultKey: '⌘ + L',
                currentKey: '⌘ + L',
                category: 'conversation',
                enabled: true,
            },
            {
                id: 'clear-context',
                name: '清除上下文',
                description: '清除对话的上下文记忆',
                defaultKey: '⌘ + K',
                currentKey: '⌘ + K',
                category: 'conversation',
                enabled: true,
            },
            {
                id: 'search-previous',
                name: '在当前对话中搜索消息',
                description: '在当前对话历史中搜索特定消息',
                defaultKey: '⌘ + F',
                currentKey: '⌘ + F',
                category: 'conversation',
                enabled: true,
            },
        ],
        globalShortcut: 'CommandOrControl+Shift+K',
        newNote: 'CommandOrControl+N',
        search: 'CommandOrControl+F',
        quickCapture: 'CommandOrControl+Shift+N',
        toggleSidebar: 'CommandOrControl+B',
    },
    document: {
        ocrProvider: '系统OCR',
        ocrLanguages: [],
        documentProvider: 'MinerU',
        apiKey: '',
        apiUrl: 'https://mineru.net',
        documents: [],
        autoSave: true,
        autoSaveInterval: 30,
        defaultFormat: 'markdown',
        enableVersionControl: true,
        maxVersions: 10,
    },
    data: {
        dataDirectory: '',
        databasePath: '',
        attachmentsPath: '',
        logsPath: '',
        backupEnabled: true,
        backupInterval: 24,
        maxBackups: 7,
    },
    mcp: {
        enabled: false,
        servers: [],
    },
    memory: {
        enabled: true,
        maxMemoryItems: 1000,
        retentionDays: 30,
        autoCleanup: true,
        userManagementEnabled: true,
        selectedUser: 'default',
    },
};