import { ProviderConfig } from './types';

export const initialProviders: ProviderConfig[] = [
  {
    id: 'modelscope',
    name: '魔搭',
    icon: 'modelscope',
    enabled: true,
    apiKey: '',
    apiUrl: 'https://api-inference.modelscope.cn/v1/',
    description: '魔搭社区 v1 版本',
    models: [
      {
        id: 'qwen2.5-72b-instruct',
        name: 'Qwen/Qwen2.5-72B-Instruct',
        displayName: 'Qwen2.5-72B-Instruct',
        status: 'available',
        maxTokens: 8192,
        supportStream: true,
      },
      {
        id: 'qwen2.5-vl-72b-instruct',
        name: 'Qwen/Qwen2.5-VL-72B-Instruct',
        displayName: 'Qwen2.5-VL-72B-Instruct',
        status: 'available',
        maxTokens: 8192,
        supportStream: true,
      },
      {
        id: 'qwen2.5-coder-32b-instruct',
        name: 'Qwen/Qwen2.5-Coder-32B-Instruct',
        displayName: 'Qwen2.5-Coder-32B-Instruct',
        status: 'available',
        maxTokens: 8192,
        supportStream: true,
      },
    ],
  },
  {
    id: 'siliconflow',
    name: '硅基流动',
    icon: 'siliconflow',
    enabled: false,
    apiKey: '',
    apiUrl: 'https://api.siliconflow.cn/v1/',
    models: [],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: 'openrouter',
    enabled: false,
    apiKey: '',
    apiUrl: 'https://openrouter.ai/api/v1/',
    models: [],
  },
  {
    id: 'o3',
    name: 'O3',
    icon: 'o3',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    icon: 'aihubmix',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'deepseek',
    name: '深度求索',
    icon: 'deepseek',
    enabled: false,
    apiKey: '',
    apiUrl: 'https://api.deepseek.com/v1/',
    models: [
      {
        id: 'deepseek-r1',
        name: 'deepseek-ai/DeepSeek-R1',
        displayName: 'DeepSeek-R1',
        status: 'available',
        supportStream: true,
      },
      {
        id: 'deepseek-v3',
        name: 'deepseek-ai/DeepSeek-V3',
        displayName: 'DeepSeek-V3',
        status: 'available',
        supportStream: true,
      },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: 'ollama',
    enabled: false,
    apiKey: '',
    apiUrl: 'http://localhost:11434/v1/',
    models: [],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: 'anthropic',
    enabled: false,
    apiKey: '',
    apiUrl: 'https://api.anthropic.com/v1/',
    models: [],
  },
  {
    id: 'aionly',
    name: '唯一—AI',
    icon: 'aihubmix',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: 'openai',
    enabled: false,
    apiKey: '',
    apiUrl: 'https://api.openai.com/v1/',
    models: [],
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    icon: 'azure',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'ppio',
    name: 'PPIO 派欧云',
    icon: 'ppio',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'burncloud',
    name: 'BurnCloud',
    icon: 'burncloud',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'cephalon',
    name: 'Cephalon',
    icon: 'cephalon',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'phb',
    name: 'PH8 大模型开放平台',
    icon: 'phb',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'ai302',
    name: '302.AI',
    icon: 'ai302',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'newapi',
    name: 'New API',
    icon: 'newapi',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'lanketech',
    name: '蓝科技',
    icon: 'cherryin',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
  {
    id: 'wuxin',
    name: '无问芯穹',
    icon: 'cherryin',
    enabled: false,
    apiKey: '',
    apiUrl: '',
    models: [],
  },
];

